name: LoveAuth
version: '${version}'
main: me.lovelace.loveAuth.LoveAuth
api-version: '26.2'
authors: [ Lovelace ]
depend: []
softdepend: [ PlaceholderAPI ]
commands:
  loveauth:
    aliases: [ auth, авторизация, регистрация, вход ]
    description: Главная команда LoveAuth
    usage: /loveauth <подкоманда>
  loveauthadmin:
    aliases: [ ладмин ]
    description: Панель администратора LoveAuth
    usage: /loveauthadmin <подкоманда>
  ladmin:
    description: (устарело) переехала в /loveauthadmin
    usage: /loveauthadmin <подкоманда>
permissions:
  loveauth.admin:
    description: Полный доступ к административным командам LoveAuth
    default: op
    children:
      loveauth.reload: true
  loveauth.reload:
    description: Перезагрузка конфигурации LoveAuth (/loveauthadmin reload)
    default: op
  loveauth.queue.bypass:
    description: Пропуск очереди
    default: false
  loveauth.queue.priority.<число>:
    description: Приоритет в очереди (меньше = выше)
    default: false
